In [15]:
import os
import sys
import copy
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from src.data.datahandler import DataHandler
import os
import logging
import time

In [16]:
input_file = os.path.join("D:\\", "projects", "nmf_py", "data", "Dataset-BatonRouge-con.csv")
uncertainty_file = os.path.join("D:\\", "projects", "nmf_py", "data", "Dataset-BatonRouge-unc.csv")
output_path = os.path.join("D:\\", "projects", "nmf_py", "output", "BatonRouge")

In [17]:
quantile = 0.98
drop_max = True
drop_min = False

index_col = "Date"

In [34]:
dh = DataHandler(
        input_path=input_file,
        uncertainty_path=uncertainty_file,
        output_path=output_path,
        index_col=index_col
    )
dh.input_data

06-Apr-23 14:20:33 - Input and output configured successfully

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
Date,,,,,,,,,,,,,,,,,,,,,
6/1/2005 6:00,0.530000,1.560001,0.460000,0.580000,0.230000,0.370,0.450000,2.460002,2.060001,1.980001,...,0.005000,1.020001,17.760011,19.200012,0.390000,3.290002,0.005000,1.400001,31.732815,166.81290
6/2/2005 3:00,2.730002,4.650003,2.550002,1.440001,0.880001,0.760,1.840001,3.680002,2.620002,3.560002,...,0.730000,2.160001,14.370009,6.200004,0.750000,12.090008,2.410002,2.220001,119.645604,272.54570
6/2/2005 6:00,1.290001,4.660003,1.270001,2.070001,0.970001,0.550,1.480001,3.880002,2.490002,3.340002,...,0.410000,1.200001,19.690012,4.210003,0.430000,6.120004,0.530000,1.300001,23.178396,188.67350
6/3/2005 3:00,4.170003,6.790004,2.180001,0.800001,1.030001,0.790,2.120001,4.940003,4.490003,5.400003,...,1.330001,3.510002,15.920010,3.680002,1.910001,16.760010,0.280000,1.850001,77.234221,282.63435
6/4/2005 3:00,1.580001,2.550002,0.810001,1.000001,0.540000,0.380,1.080001,2.110001,2.080001,2.920002,...,0.610000,1.600001,14.160009,2.540002,0.590000,7.490005,0.005000,0.940001,30.553975,149.97405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9/24/2006 6:00,0.290000,2.240001,0.620000,4.610003,0.600000,0.170,0.970001,11.940007,0.410000,3.250002,...,0.090000,0.470000,39.240025,4.520003,1.040001,3.020002,0.360000,2.880002,47.594851,285.96500
9/25/2006 6:00,0.550000,1.760001,0.470000,3.120002,0.400000,0.300,1.130001,6.330004,1.360001,1.150001,...,0.005000,0.590000,8.190005,1.060001,0.550000,2.720002,0.230000,1.080001,47.734946,134.10000
9/26/2006 3:00,0.680000,1.390001,0.460000,0.410000,0.005000,0.005,1.060001,0.920001,1.360001,1.180001,...,0.005000,0.530000,4.750003,0.800001,0.400000,2.620002,0.005000,0.300000,25.639976,64.75500
9/26/2006 6:00,1.140001,2.760002,0.860001,0.990001,0.470000,0.300,0.990001,2.090001,3.480002,2.040001,...,0.410000,1.040001,10.040006,2.080001,0.340000,5.260003,0.005000,0.680000,39.664953,113.99000
9/28/2006 3:00,2.600002,4.110003,1.460001,6.260004,0.830001,0.670,1.760001,15.260010,3.090002,3.950002,...,0.550000,2.100001,19.730012,3.480002,0.880001,9.460006,0.340000,1.830001,8.134884,193.57500

In [35]:
# dh.remove_outliers(quantile=quantile, drop_min=drop_min, drop_max=drop_max)
# dh.input_data_processed[:2]

In [20]:
# dh.min_values

In [21]:
# dh.max_values

In [22]:
# dh.input_data.max()

In [36]:
# dh.scale()
sn = dh.input_data_processed / dh.uncertainty_data_processed
sn.shape

(307, 41)

In [45]:
data_mask = dh.input_data_processed.mask(sn < 2.0, 0.5)
data_mask = data_mask.mask(sn >= 2, 1.0)
data_mask

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
Date,,,,,,,,,,,,,,,,,,,,,
6/1/2005 6:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,0.5
6/2/2005 3:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
6/2/2005 6:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
6/3/2005 3:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
6/4/2005 3:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9/24/2006 6:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
9/25/2006 6:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
9/26/2006 3:00,1.0,1.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,1.0,...,0.5,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,0.5
9/26/2006 6:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,0.5
9/28/2006 3:00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5

In [10]:
import numpy as np

np.max(dh.input_data_processed, axis=0)

array([0.99999994, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99999994, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.99999994, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.23004015], dtype=float32)

In [11]:


scale_test = np.subtract(dh.input_data_processed, dh.min_values.to_numpy())
scale_test.shape

(224, 41)

In [14]:
dh.input_data_processed

array([[0.4165316 , 0.6379274 , 0.44620812, ..., 0.20604613, 0.09570183,
        0.08642592],
       [0.5105348 , 0.34521747, 0.2839506 , ..., 0.1487669 , 0.12684028,
        0.0632401 ],
       [0.31604537, 0.1565513 , 0.13580248, ..., 0.09626094, 0.18863145,
        0.06292622],
       ...,
       [0.17666127, 0.23562461, 0.16402116, ..., 0.17104216, 0.1993754 ,
        0.05372956],
       [0.21880065, 0.18429631, 0.16049382, ..., 0.04693715, 0.1060942 ,
        0.01218321],
       [0.36790922, 0.3743497 , 0.3015873 , ..., 0.10739857, 0.16530527,
        0.04168114]], dtype=float32)