In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
wash_conc_file = "D:\\projects\\nmf_py\\user_data\\wash_con_1.csv"
wash_unc_file = "D:\\projects\\nmf_py\\user_data\\wash_unc_1.csv"

In [3]:
wash_conc_df = pd.read_csv(wash_conc_file)
wash_conc_labels = [col for col in wash_conc_df.columns if "val" in col]
wash_conc_labels.insert(0, "obs_date")
wash_conc_df = wash_conc_df[wash_conc_labels]
wash_conc_df["obs_date"] = pd.to_datetime(wash_conc_df["obs_date"], format="%Y%m%d")
wash_conc_df.set_index("obs_date", inplace=True)
wash_conc_df

,ALf_val,ASf_val,BRf_val,CAf_val,CHLf_val,CLf_val,CRf_val,CUf_val,ECf_val,EC1f_val,...,CM_val,CM_bext_val,dv_val,ECf_bext_val,ammNO3f_val,ammNO3f_bext_val,RCFM_val,SOILf_val,SOILf_bext_val,OMCf_val
obs_date,,,,,,,,,,,,,,,,,,,,,
1988-08-31,0.05638,0.00000,0.00506,0.07695,0.1385,0.0,0.00000,0.00781,3.4034,3.7525,...,6.33932,3.80359,26.73704,34.034,1.58606,15.98743,16.84729,1.10076,1.10076,4.67460
1988-09-07,0.04586,0.00000,0.00583,0.05573,-999.0000,0.0,0.00000,0.00470,-999.0000,-999.0000,...,5.55478,3.33287,-999.00000,-999.000,-999.00000,-999.00000,-999.00000,0.83679,0.83679,-999.00000
1988-09-10,0.09276,0.00000,0.00879,0.07595,0.0998,0.0,0.00227,0.00677,2.0428,2.4607,...,-999.00000,-999.00000,-999.00000,20.428,1.01962,10.46126,35.96972,1.36909,1.36909,6.26500
1988-09-14,0.07211,0.00000,0.00387,0.10184,0.0442,0.0,0.00000,0.00690,1.6568,1.7162,...,7.92086,4.75252,24.19103,16.568,0.49781,5.10754,12.71179,1.48908,1.48908,2.97094
1988-09-17,0.00000,0.00000,0.00814,0.05338,0.2719,0.0,0.00000,0.00505,1.3619,1.5559,...,9.09144,5.45486,22.76636,13.619,1.50891,15.48145,10.60624,0.59655,0.59655,3.34796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002-05-14,0.00000,0.00030,0.00223,0.03409,-0.0387,0.0,0.00000,0.00190,0.3689,0.3719,...,4.37770,2.62662,19.75898,3.689,0.20459,1.84135,7.88923,0.66480,0.66480,1.30984
2002-05-17,0.00000,0.00000,0.00614,0.06067,-0.2049,0.0,0.00061,0.00388,1.0164,0.8584,...,7.35920,4.41552,28.07941,10.164,1.22305,11.00744,20.64797,1.19139,1.19139,5.19498
2002-05-20,0.00000,0.00074,0.00321,0.02642,-0.1132,0.0,0.00061,0.00284,0.5679,0.5149,...,2.63640,1.58184,19.75261,5.679,0.78406,7.05656,7.95640,0.54755,0.54755,1.45838
2002-05-23,0.00000,0.00075,0.00378,0.05104,-0.2926,0.0,0.00049,0.00234,0.7446,0.6087,...,6.17490,3.70494,22.72161,7.446,1.04258,9.38320,11.44251,0.72020,0.72020,2.93342
2002-05-26,0.00000,0.00064,0.00778,0.04779,-0.4080,0.0,0.00040,0.00219,0.8122,0.6650,...,7.76810,4.66086,29.68293,8.122,1.15765,10.41881,23.60049,0.96347,0.96347,5.11658

In [4]:
wash_unc_df = pd.read_csv(wash_unc_file)
wash_unc_labels = [col for col in wash_unc_df.columns if "unc" in col]
wash_unc_labels.insert(0, "obs_date")
wash_unc_df = wash_unc_df[wash_unc_labels]
wash_unc_df["obs_date"] = pd.to_datetime(wash_unc_df["obs_date"], format="%Y%m%d")
wash_unc_df.set_index("obs_date", inplace=True)
wash_unc_df

,ALf_unc,ASf_unc,BRf_unc,CAf_unc,CHLf_unc,CLf_unc,CRf_unc,CUf_unc,ECf_unc,EC1f_unc,...,CM_unc,CM_bext_unc,dv_unc,ECf_bext_unc,ammNO3f_unc,ammNO3f_bext_unc,RCFM_unc,SOILf_unc,SOILf_bext_unc,OMCf_unc
obs_date,,,,,,,,,,,,,,,,,,,,,
1988-08-31,0.00667,0.00000,0.00063,0.00491,0.0302,0.0,0.00000,0.00057,-999,0.5049,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-07,0.00644,0.00000,0.00078,0.00442,-999.0000,0.0,0.00000,0.00062,-999,-999.0000,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-10,0.01222,0.00000,0.00099,0.00606,0.0290,0.0,0.00099,0.00075,-999,0.3330,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-14,0.00614,0.00000,0.00039,0.00596,0.0284,0.0,0.00000,0.00047,-999,0.2335,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-17,0.00000,0.00000,0.00094,0.00452,0.0329,0.0,0.00000,0.00064,-999,0.2122,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002-05-14,0.00000,0.00011,0.00014,0.00215,0.0303,0.0,0.00000,0.00014,-999,0.0502,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-17,0.00000,0.00000,0.00033,0.00342,0.0264,0.0,0.00013,0.00024,-999,0.1148,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-20,0.00000,0.00012,0.00018,0.00162,0.0268,0.0,0.00011,0.00018,-999,0.0691,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-23,0.00000,0.00013,0.00021,0.00295,0.0222,0.0,0.00025,0.00016,-999,0.0815,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-26,0.00000,0.00014,0.00041,0.00262,0.0213,0.0,0.00009,0.00015,-999,0.0890,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [5]:
val_medians = wash_conc_df.median()
val_medians

ALf_val               0.026205
ASf_val               0.000000
BRf_val               0.004140
CAf_val               0.036980
CHLf_val              0.022100
CLf_val               0.000000
CRf_val               0.000000
CUf_val               0.003250
ECf_val               1.111250
EC1f_val              1.141850
EC2f_val              0.094300
EC3f_val              0.011700
FEf_val               0.097105
Hf_val                0.673830
Kf_val                0.051880
MF_val               14.904165
MGf_val               0.000000
MNf_val               0.001235
MOf_val            -999.000000
MT_val               20.211880
N2f_val              -0.003300
NAf_val               0.083130
NH4f_val           -999.000000
NIf_val               0.000610
NO3f_val              1.007950
OCf_val               2.543750
OC1f_val              0.286600
OC2f_val              0.513600
OC3f_val              0.715700
OC4f_val              0.779800
OPf_val               0.115450
Pf_val                0.000000
PBf_val               0.004780
RBf_val               0.000000
Sf_val                1.417700
SEf_val               0.001845
SIf_val               0.099030
SO4f_val              3.881100
SRf_val               0.000510
TIf_val               0.007530
Vf_val                0.002675
ZNf_val               0.013360
ZRf_val               0.000000
SO2_val            -999.000000
ammSO4f_val           5.855995
ammSO4f_bext_val     49.982560
aerosol_bext_val     89.961045
CM_val                5.116550
CM_bext_val           3.069930
dv_val               23.021950
ECf_bext_val         11.112500
ammNO3f_val           1.300255
ammNO3f_bext_val     11.473105
RCFM_val             13.011180
SOILf_val             0.647045
SOILf_bext_val        0.647045
OMCf_val              3.561250
dtype: float64

In [6]:
drop_columns = {k: v for k, v in val_medians.items() if v == -999.0}
drop_columns

{'MOf_val': -999.0, 'NH4f_val': -999.0, 'SO2_val': -999.0}

In [7]:
wash_conc_df.drop(labels=drop_columns.keys(), inplace=True, axis=1)
wash_conc_df

,ALf_val,ASf_val,BRf_val,CAf_val,CHLf_val,CLf_val,CRf_val,CUf_val,ECf_val,EC1f_val,...,CM_val,CM_bext_val,dv_val,ECf_bext_val,ammNO3f_val,ammNO3f_bext_val,RCFM_val,SOILf_val,SOILf_bext_val,OMCf_val
obs_date,,,,,,,,,,,,,,,,,,,,,
1988-08-31,0.05638,0.00000,0.00506,0.07695,0.1385,0.0,0.00000,0.00781,3.4034,3.7525,...,6.33932,3.80359,26.73704,34.034,1.58606,15.98743,16.84729,1.10076,1.10076,4.67460
1988-09-07,0.04586,0.00000,0.00583,0.05573,-999.0000,0.0,0.00000,0.00470,-999.0000,-999.0000,...,5.55478,3.33287,-999.00000,-999.000,-999.00000,-999.00000,-999.00000,0.83679,0.83679,-999.00000
1988-09-10,0.09276,0.00000,0.00879,0.07595,0.0998,0.0,0.00227,0.00677,2.0428,2.4607,...,-999.00000,-999.00000,-999.00000,20.428,1.01962,10.46126,35.96972,1.36909,1.36909,6.26500
1988-09-14,0.07211,0.00000,0.00387,0.10184,0.0442,0.0,0.00000,0.00690,1.6568,1.7162,...,7.92086,4.75252,24.19103,16.568,0.49781,5.10754,12.71179,1.48908,1.48908,2.97094
1988-09-17,0.00000,0.00000,0.00814,0.05338,0.2719,0.0,0.00000,0.00505,1.3619,1.5559,...,9.09144,5.45486,22.76636,13.619,1.50891,15.48145,10.60624,0.59655,0.59655,3.34796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002-05-14,0.00000,0.00030,0.00223,0.03409,-0.0387,0.0,0.00000,0.00190,0.3689,0.3719,...,4.37770,2.62662,19.75898,3.689,0.20459,1.84135,7.88923,0.66480,0.66480,1.30984
2002-05-17,0.00000,0.00000,0.00614,0.06067,-0.2049,0.0,0.00061,0.00388,1.0164,0.8584,...,7.35920,4.41552,28.07941,10.164,1.22305,11.00744,20.64797,1.19139,1.19139,5.19498
2002-05-20,0.00000,0.00074,0.00321,0.02642,-0.1132,0.0,0.00061,0.00284,0.5679,0.5149,...,2.63640,1.58184,19.75261,5.679,0.78406,7.05656,7.95640,0.54755,0.54755,1.45838
2002-05-23,0.00000,0.00075,0.00378,0.05104,-0.2926,0.0,0.00049,0.00234,0.7446,0.6087,...,6.17490,3.70494,22.72161,7.446,1.04258,9.38320,11.44251,0.72020,0.72020,2.93342
2002-05-26,0.00000,0.00064,0.00778,0.04779,-0.4080,0.0,0.00040,0.00219,0.8122,0.6650,...,7.76810,4.66086,29.68293,8.122,1.15765,10.41881,23.60049,0.96347,0.96347,5.11658

In [8]:
unc_drop_columns = [col.replace("val", "unc") for col in drop_columns.keys()]
wash_unc_df.drop(labels=unc_drop_columns, inplace=True, axis=1)
wash_unc_df

,ALf_unc,ASf_unc,BRf_unc,CAf_unc,CHLf_unc,CLf_unc,CRf_unc,CUf_unc,ECf_unc,EC1f_unc,...,CM_unc,CM_bext_unc,dv_unc,ECf_bext_unc,ammNO3f_unc,ammNO3f_bext_unc,RCFM_unc,SOILf_unc,SOILf_bext_unc,OMCf_unc
obs_date,,,,,,,,,,,,,,,,,,,,,
1988-08-31,0.00667,0.00000,0.00063,0.00491,0.0302,0.0,0.00000,0.00057,-999,0.5049,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-07,0.00644,0.00000,0.00078,0.00442,-999.0000,0.0,0.00000,0.00062,-999,-999.0000,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-10,0.01222,0.00000,0.00099,0.00606,0.0290,0.0,0.00099,0.00075,-999,0.3330,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-14,0.00614,0.00000,0.00039,0.00596,0.0284,0.0,0.00000,0.00047,-999,0.2335,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1988-09-17,0.00000,0.00000,0.00094,0.00452,0.0329,0.0,0.00000,0.00064,-999,0.2122,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002-05-14,0.00000,0.00011,0.00014,0.00215,0.0303,0.0,0.00000,0.00014,-999,0.0502,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-17,0.00000,0.00000,0.00033,0.00342,0.0264,0.0,0.00013,0.00024,-999,0.1148,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-20,0.00000,0.00012,0.00018,0.00162,0.0268,0.0,0.00011,0.00018,-999,0.0691,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-23,0.00000,0.00013,0.00021,0.00295,0.0222,0.0,0.00025,0.00016,-999,0.0815,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2002-05-26,0.00000,0.00014,0.00041,0.00262,0.0213,0.0,0.00009,0.00015,-999,0.0890,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [9]:
conc_columns = {}
for col in wash_conc_df.columns:
    conc_columns[col] = col.split("_val")[0]
wash_conc_df.rename(columns=conc_columns, inplace=True)

In [10]:
wash_conc_df.replace(-999.0, np.nan, inplace=True)
wash_conc_df.fillna(wash_conc_df.median(), inplace=True)
wash_conc_df[wash_conc_df == 0.0] = 1e-15
wash_conc_df

,ALf,ASf,BRf,CAf,CHLf,CLf,CRf,CUf,ECf,EC1f,...,CM,CM_bext,dv,ECf_bext,ammNO3f,ammNO3f_bext,RCFM,SOILf,SOILf_bext,OMCf
obs_date,,,,,,,,,,,,,,,,,,,,,
1988-08-31,5.638000e-02,1.000000e-15,0.00506,0.07695,0.13850,1.000000e-15,1.000000e-15,0.00781,3.4034,3.7525,...,6.33932,3.80359,26.737040,34.034,1.58606,15.98743,16.84729,1.10076,1.10076,4.67460
1988-09-07,4.586000e-02,1.000000e-15,0.00583,0.05573,0.04435,1.000000e-15,1.000000e-15,0.00470,1.1363,1.1716,...,5.55478,3.33287,24.225285,11.363,1.46518,12.90470,13.82829,0.83679,0.83679,3.61032
1988-09-10,9.276000e-02,1.000000e-15,0.00879,0.07595,0.09980,1.000000e-15,2.270000e-03,0.00677,2.0428,2.4607,...,5.57144,3.34286,24.225285,20.428,1.01962,10.46126,35.96972,1.36909,1.36909,6.26500
1988-09-14,7.211000e-02,1.000000e-15,0.00387,0.10184,0.04420,1.000000e-15,1.000000e-15,0.00690,1.6568,1.7162,...,7.92086,4.75252,24.191030,16.568,0.49781,5.10754,12.71179,1.48908,1.48908,2.97094
1988-09-17,1.000000e-15,1.000000e-15,0.00814,0.05338,0.27190,1.000000e-15,1.000000e-15,0.00505,1.3619,1.5559,...,9.09144,5.45486,22.766360,13.619,1.50891,15.48145,10.60624,0.59655,0.59655,3.34796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002-05-14,1.000000e-15,3.000000e-04,0.00223,0.03409,-0.03870,1.000000e-15,1.000000e-15,0.00190,0.3689,0.3719,...,4.37770,2.62662,19.758980,3.689,0.20459,1.84135,7.88923,0.66480,0.66480,1.30984
2002-05-17,1.000000e-15,1.000000e-15,0.00614,0.06067,-0.20490,1.000000e-15,6.100000e-04,0.00388,1.0164,0.8584,...,7.35920,4.41552,28.079410,10.164,1.22305,11.00744,20.64797,1.19139,1.19139,5.19498
2002-05-20,1.000000e-15,7.400000e-04,0.00321,0.02642,-0.11320,1.000000e-15,6.100000e-04,0.00284,0.5679,0.5149,...,2.63640,1.58184,19.752610,5.679,0.78406,7.05656,7.95640,0.54755,0.54755,1.45838
2002-05-23,1.000000e-15,7.500000e-04,0.00378,0.05104,-0.29260,1.000000e-15,4.900000e-04,0.00234,0.7446,0.6087,...,6.17490,3.70494,22.721610,7.446,1.04258,9.38320,11.44251,0.72020,0.72020,2.93342
2002-05-26,1.000000e-15,6.400000e-04,0.00778,0.04779,-0.40800,1.000000e-15,4.000000e-04,0.00219,0.8122,0.6650,...,7.76810,4.66086,29.682930,8.122,1.15765,10.41881,23.60049,0.96347,0.96347,5.11658

In [11]:
unc_columns = {}
for col in wash_unc_df.columns:
    unc_columns[col] = col.split("_unc")[0]
wash_unc_df.rename(columns=unc_columns, inplace=True)

In [12]:
wash_unc_df.replace(-999.0, np.nan, inplace=True)
unc_mod = wash_conc_df * 0.06
wash_unc_df.update(unc_mod)
wash_unc_df = wash_unc_df.abs() + 1e-15
wash_unc_df

,ALf,ASf,BRf,CAf,CHLf,CLf,CRf,CUf,ECf,EC1f,...,CM,CM_bext,dv,ECf_bext,ammNO3f,ammNO3f_bext,RCFM,SOILf,SOILf_bext,OMCf
obs_date,,,,,,,,,,,,,,,,,,,,,
1988-08-31,3.382800e-03,1.060000e-15,0.000304,0.004617,0.008310,1.060000e-15,1.060000e-15,0.000469,0.204204,0.225150,...,0.380359,0.228215,1.604222,2.04204,0.095164,0.959246,1.010837,0.066046,0.066046,0.280476
1988-09-07,2.751600e-03,1.060000e-15,0.000350,0.003344,0.002661,1.060000e-15,1.060000e-15,0.000282,0.068178,0.070296,...,0.333287,0.199972,1.453517,0.68178,0.087911,0.774282,0.829697,0.050207,0.050207,0.216619
1988-09-10,5.565600e-03,1.060000e-15,0.000527,0.004557,0.005988,1.060000e-15,1.362000e-04,0.000406,0.122568,0.147642,...,0.334286,0.200572,1.453517,1.22568,0.061177,0.627676,2.158183,0.082145,0.082145,0.375900
1988-09-14,4.326600e-03,1.060000e-15,0.000232,0.006110,0.002652,1.060000e-15,1.060000e-15,0.000414,0.099408,0.102972,...,0.475252,0.285151,1.451462,0.99408,0.029869,0.306452,0.762707,0.089345,0.089345,0.178256
1988-09-17,1.060000e-15,1.060000e-15,0.000488,0.003203,0.016314,1.060000e-15,1.060000e-15,0.000303,0.081714,0.093354,...,0.545486,0.327292,1.365982,0.81714,0.090535,0.928887,0.636374,0.035793,0.035793,0.200878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002-05-14,1.060000e-15,1.800000e-05,0.000134,0.002045,0.002322,1.060000e-15,1.060000e-15,0.000114,0.022134,0.022314,...,0.262662,0.157597,1.185539,0.22134,0.012275,0.110481,0.473354,0.039888,0.039888,0.078590
2002-05-17,1.060000e-15,1.060000e-15,0.000368,0.003640,0.012294,1.060000e-15,3.660000e-05,0.000233,0.060984,0.051504,...,0.441552,0.264931,1.684765,0.60984,0.073383,0.660446,1.238878,0.071483,0.071483,0.311699
2002-05-20,1.060000e-15,4.440000e-05,0.000193,0.001585,0.006792,1.060000e-15,3.660000e-05,0.000170,0.034074,0.030894,...,0.158184,0.094910,1.185157,0.34074,0.047044,0.423394,0.477384,0.032853,0.032853,0.087503
2002-05-23,1.060000e-15,4.500000e-05,0.000227,0.003062,0.017556,1.060000e-15,2.940000e-05,0.000140,0.044676,0.036522,...,0.370494,0.222296,1.363297,0.44676,0.062555,0.562992,0.686551,0.043212,0.043212,0.176005
2002-05-26,1.060000e-15,3.840000e-05,0.000467,0.002867,0.024480,1.060000e-15,2.400000e-05,0.000131,0.048732,0.039900,...,0.466086,0.279652,1.780976,0.48732,0.069459,0.625129,1.416029,0.057808,0.057808,0.306995

In [13]:
cleaned_wash_conc_file = "D:\\projects\\nmf_py\\user_data\\wash_con_cleaned.csv"
cleaned_wash_unc_file = "D:\\projects\\nmf_py\\user_data\\wash_unc_cleaned.csv"
wash_conc_df.to_csv(cleaned_wash_conc_file)
wash_unc_df.to_csv(cleaned_wash_unc_file)

In [14]:
wash_conc_df.describe()

,ALf,ASf,BRf,CAf,CHLf,CLf,CRf,CUf,ECf,EC1f,...,CM,CM_bext,dv,ECf_bext,ammNO3f,ammNO3f_bext,RCFM,SOILf,SOILf_bext,OMCf
count,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1374.000000,1374.000000,...,1.374000e+03,1.374000e+03,1374.000000,1374.000000,1.374000e+03,1.374000e+03,1374.000000,1374.000000,1374.000000,1374.000000
mean,4.134995e-02,4.385444e-04,4.731965e-03,4.385769e-02,7.853559e-02,5.746288e-03,6.274017e-04,3.920502e-03,1.327020,1.434122,...,6.572195e+00,3.943317e+00,24.336597,13.270205,2.010022e+00,1.716460e+01,15.206144,0.776186,0.776186,4.106670
std,6.788242e-02,5.878106e-04,2.703555e-03,3.404476e-02,2.383328e-01,6.413658e-02,1.175263e-03,2.902807e-03,0.785948,0.974642,...,5.120771e+00,3.072462e+00,4.076772,7.859478,1.781735e+00,1.460530e+01,6.843847,0.605193,0.605193,2.356610
min,1.000000e-15,1.000000e-15,1.000000e-15,1.000000e-15,-7.921000e-01,1.000000e-15,1.000000e-15,1.000000e-15,0.193900,0.218500,...,1.000000e-15,1.000000e-15,9.947440,1.939000,1.000000e-15,1.000000e-15,2.331500,0.101880,0.101880,0.613480
25%,1.000000e-15,1.000000e-15,2.950000e-03,2.736500e-02,1.000000e-15,1.000000e-15,1.000000e-15,2.340000e-03,0.780500,0.790025,...,3.806500e+00,2.283900e+00,21.978750,7.805000,8.344675e-01,7.512055e+00,10.418485,0.467243,0.467243,2.486085
50%,2.706000e-02,1.000000e-15,4.160000e-03,3.728000e-02,4.435000e-02,1.000000e-15,1.000000e-15,3.280000e-03,1.136300,1.171600,...,5.571440e+00,3.342860e+00,24.225285,11.363000,1.465180e+00,1.290470e+01,13.828290,0.650770,0.650770,3.610320
75%,6.065500e-02,8.100000e-04,5.750000e-03,5.149000e-02,1.195750e-01,1.000000e-15,9.100000e-04,4.680000e-03,1.616900,1.762700,...,7.921670e+00,4.753000e+00,26.830400,16.169000,2.518947e+00,2.155973e+01,18.695087,0.927985,0.927985,5.088230
max,1.083530e+00,4.300000e-03,3.412000e-02,5.917600e-01,1.950100e+00,1.333370e+00,8.410000e-03,5.743000e-02,5.774600,7.679200,...,6.101307e+01,3.660784e+01,37.788530,57.746010,1.489279e+01,1.242059e+02,46.699320,8.874290,8.874290,24.384780

In [15]:
wash_unc_df.describe()

,ALf,ASf,BRf,CAf,CHLf,CLf,CRf,CUf,ECf,EC1f,...,CM,CM_bext,dv,ECf_bext,ammNO3f,ammNO3f_bext,RCFM,SOILf,SOILf_bext,OMCf
count,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1.374000e+03,1374.000000,1374.000000,...,1.374000e+03,1.374000e+03,1374.000000,1374.000000,1.374000e+03,1.374000e+03,1374.000000,1374.000000,1374.000000,1374.000000
mean,2.480997e-03,2.631266e-05,2.839179e-04,2.631461e-03,8.397489e-03,3.447773e-04,3.764410e-05,2.352301e-04,0.079621,0.086047,...,3.943317e-01,2.365990e-01,1.460196,0.796212,1.206013e-01,1.029876e+00,0.912369,0.046571,0.046571,0.246400
std,4.072945e-03,3.526863e-05,1.622133e-04,2.042686e-03,1.249561e-02,3.848195e-03,7.051575e-05,1.741684e-04,0.047157,0.058479,...,3.072462e-01,1.843477e-01,0.244606,0.471569,1.069041e-01,8.763178e-01,0.410631,0.036312,0.036312,0.141397
min,1.060000e-15,1.060000e-15,1.060000e-15,1.060000e-15,1.060000e-15,1.060000e-15,1.060000e-15,1.060000e-15,0.011634,0.013110,...,1.060000e-15,1.060000e-15,0.596846,0.116340,1.060000e-15,1.060000e-15,0.139890,0.006113,0.006113,0.036809
25%,1.060000e-15,1.060000e-15,1.770000e-04,1.641900e-03,1.845000e-03,1.060000e-15,1.060000e-15,1.404000e-04,0.046830,0.047402,...,2.283900e-01,1.370340e-01,1.318725,0.468300,5.006805e-02,4.507233e-01,0.625109,0.028035,0.028035,0.149165
50%,1.623600e-03,1.060000e-15,2.496000e-04,2.236800e-03,3.300000e-03,1.060000e-15,1.060000e-15,1.968000e-04,0.068178,0.070296,...,3.342864e-01,2.005716e-01,1.453517,0.681780,8.791080e-02,7.742820e-01,0.829697,0.039046,0.039046,0.216619
75%,3.639300e-03,4.860000e-05,3.450000e-04,3.089400e-03,9.676500e-03,1.060000e-15,5.460000e-05,2.808000e-04,0.097014,0.105762,...,4.753002e-01,2.851800e-01,1.609824,0.970140,1.511369e-01,1.293584e+00,1.121705,0.055679,0.055679,0.305294
max,6.501180e-02,2.580000e-04,2.047200e-03,3.550560e-02,1.170060e-01,8.000220e-02,5.046000e-04,3.445800e-03,0.346476,0.460752,...,3.660784e+00,2.196470e+00,2.267312,3.464761,8.935674e-01,7.452354e+00,2.801959,0.532457,0.532457,1.463087