In [1]:
import os
import sys
import copy
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from esat.data.datahandler import DataHandler
import os
import logging
import time

In [2]:
input_file = os.path.join("D:\\", "projects", "nmf_py", "data", "Dataset-BatonRouge-con.csv")
uncertainty_file = os.path.join("D:\\", "projects", "nmf_py", "data", "Dataset-BatonRouge-unc.csv")
output_path = os.path.join("D:\\", "projects", "nmf_py", "output", "BatonRouge")

In [3]:
quantile = 0.98
drop_max = True
drop_min = False

index_col = "Date"

In [4]:
dh = DataHandler(
        input_path=input_file,
        uncertainty_path=uncertainty_file,
        output_path=output_path,
        index_col=index_col
    )
dh.input_data

27-Apr-23 10:30:03 - Input and output configured successfully

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
Date,,,,,,,,,,,,,,,,,,,,,
6/1/2005 6:00,0.530000,1.560001,0.460000,0.580000,0.230000,0.370,0.450000,2.460002,2.060001,1.980001,...,0.005000,1.020001,17.760011,19.200012,0.390000,3.290002,0.005000,1.400001,31.732815,166.81290
6/2/2005 3:00,2.730002,4.650003,2.550002,1.440001,0.880001,0.760,1.840001,3.680002,2.620002,3.560002,...,0.730000,2.160001,14.370009,6.200004,0.750000,12.090008,2.410002,2.220001,119.645604,272.54570
6/2/2005 6:00,1.290001,4.660003,1.270001,2.070001,0.970001,0.550,1.480001,3.880002,2.490002,3.340002,...,0.410000,1.200001,19.690012,4.210003,0.430000,6.120004,0.530000,1.300001,23.178396,188.67350
6/3/2005 3:00,4.170003,6.790004,2.180001,0.800001,1.030001,0.790,2.120001,4.940003,4.490003,5.400003,...,1.330001,3.510002,15.920010,3.680002,1.910001,16.760010,0.280000,1.850001,77.234221,282.63435
6/4/2005 3:00,1.580001,2.550002,0.810001,1.000001,0.540000,0.380,1.080001,2.110001,2.080001,2.920002,...,0.610000,1.600001,14.160009,2.540002,0.590000,7.490005,0.005000,0.940001,30.553975,149.97405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9/24/2006 6:00,0.290000,2.240001,0.620000,4.610003,0.600000,0.170,0.970001,11.940007,0.410000,3.250002,...,0.090000,0.470000,39.240025,4.520003,1.040001,3.020002,0.360000,2.880002,47.594851,285.96500
9/25/2006 6:00,0.550000,1.760001,0.470000,3.120002,0.400000,0.300,1.130001,6.330004,1.360001,1.150001,...,0.005000,0.590000,8.190005,1.060001,0.550000,2.720002,0.230000,1.080001,47.734946,134.10000
9/26/2006 3:00,0.680000,1.390001,0.460000,0.410000,0.005000,0.005,1.060001,0.920001,1.360001,1.180001,...,0.005000,0.530000,4.750003,0.800001,0.400000,2.620002,0.005000,0.300000,25.639976,64.75500
9/26/2006 6:00,1.140001,2.760002,0.860001,0.990001,0.470000,0.300,0.990001,2.090001,3.480002,2.040001,...,0.410000,1.040001,10.040006,2.080001,0.340000,5.260003,0.005000,0.680000,39.664953,113.99000
9/28/2006 3:00,2.600002,4.110003,1.460001,6.260004,0.830001,0.670,1.760001,15.260010,3.090002,3.950002,...,0.550000,2.100001,19.730012,3.480002,0.880001,9.460006,0.340000,1.830001,8.134884,193.57500

In [5]:
# dh.remove_outliers(quantile=quantile, drop_min=drop_min, drop_max=drop_max)
# dh.input_data_processed[:2]

In [6]:
# dh.min_values

In [7]:
# dh.max_values

In [8]:
# dh.input_data.max()

In [9]:
# dh.scale()
sn = dh.input_data_processed / dh.uncertainty_data_processed
sn.shape

(307, 41)

In [11]:
# data_mask = dh.input_data_processed.mask(sn < 2.0, 0.5)
# data_mask = data_mask.mask(sn >= 2, 1.0)
# data_mask

In [12]:
import numpy as np

np.max(dh.input_data_processed, axis=0)

array([  5.4700036,  13.560008 ,   4.4100027,  10.500007 ,   3.310002 ,
         2.4800014,   7.780005 ,  29.100018 ,   8.070005 ,   9.330006 ,
        21.510014 ,  19.130013 ,  49.97003  ,   3.7600024,  49.490032 ,
        36.33002  , 125.50008  ,   9.420006 ,   6.640004 ,  13.050008 ,
         1.7400011,   4.670003 ,  56.230034 ,   1.7600011,   5.3500032,
        92.56006  ,   1.9500012,   3.100002 ,  38.580025 ,   0.9400006,
         2.8600018,   1.620001 ,   5.2900033,  70.960045 ,  24.900015 ,
         7.650005 ,  26.870016 ,   3.210002 ,  17.28001  , 385.18488  ,
       708.4677   ], dtype=float32)

In [13]:


scale_test = np.subtract(dh.input_data_processed, dh.min_values.to_numpy())
scale_test.shape

(307, 41)

In [14]:
dh.input_data_processed

array([[  0.5300003 ,   1.560001  ,   0.46000028, ...,   1.4000009 ,
         31.732815  , 166.8129    ],
       [  2.7300017 ,   4.650003  ,   2.5500016 , ...,   2.2200015 ,
        119.64561   , 272.5457    ],
       [  1.2900008 ,   4.6600027 ,   1.2700008 , ...,   1.3000008 ,
         23.178396  , 188.6735    ],
       ...,
       [  0.6800004 ,   1.3900008 ,   0.46000028, ...,   0.3000002 ,
         25.639975  ,  64.755     ],
       [  1.1400007 ,   2.7600017 ,   0.86000055, ...,   0.6800004 ,
         39.664955  , 113.99      ],
       [  2.6000016 ,   4.1100025 ,   1.4600009 , ...,   1.8300011 ,
          8.134884  , 193.575     ]], dtype=float32)

In [15]:
dh.input_data

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
Date,,,,,,,,,,,,,,,,,,,,,
6/1/2005 6:00,0.530000,1.560001,0.460000,0.580000,0.230000,0.370,0.450000,2.460002,2.060001,1.980001,...,0.005000,1.020001,17.760011,19.200012,0.390000,3.290002,0.005000,1.400001,31.732815,166.81290
6/2/2005 3:00,2.730002,4.650003,2.550002,1.440001,0.880001,0.760,1.840001,3.680002,2.620002,3.560002,...,0.730000,2.160001,14.370009,6.200004,0.750000,12.090008,2.410002,2.220001,119.645604,272.54570
6/2/2005 6:00,1.290001,4.660003,1.270001,2.070001,0.970001,0.550,1.480001,3.880002,2.490002,3.340002,...,0.410000,1.200001,19.690012,4.210003,0.430000,6.120004,0.530000,1.300001,23.178396,188.67350
6/3/2005 3:00,4.170003,6.790004,2.180001,0.800001,1.030001,0.790,2.120001,4.940003,4.490003,5.400003,...,1.330001,3.510002,15.920010,3.680002,1.910001,16.760010,0.280000,1.850001,77.234221,282.63435
6/4/2005 3:00,1.580001,2.550002,0.810001,1.000001,0.540000,0.380,1.080001,2.110001,2.080001,2.920002,...,0.610000,1.600001,14.160009,2.540002,0.590000,7.490005,0.005000,0.940001,30.553975,149.97405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9/24/2006 6:00,0.290000,2.240001,0.620000,4.610003,0.600000,0.170,0.970001,11.940007,0.410000,3.250002,...,0.090000,0.470000,39.240025,4.520003,1.040001,3.020002,0.360000,2.880002,47.594851,285.96500
9/25/2006 6:00,0.550000,1.760001,0.470000,3.120002,0.400000,0.300,1.130001,6.330004,1.360001,1.150001,...,0.005000,0.590000,8.190005,1.060001,0.550000,2.720002,0.230000,1.080001,47.734946,134.10000
9/26/2006 3:00,0.680000,1.390001,0.460000,0.410000,0.005000,0.005,1.060001,0.920001,1.360001,1.180001,...,0.005000,0.530000,4.750003,0.800001,0.400000,2.620002,0.005000,0.300000,25.639976,64.75500
9/26/2006 6:00,1.140001,2.760002,0.860001,0.990001,0.470000,0.300,0.990001,2.090001,3.480002,2.040001,...,0.410000,1.040001,10.040006,2.080001,0.340000,5.260003,0.005000,0.680000,39.664953,113.99000
9/28/2006 3:00,2.600002,4.110003,1.460001,6.260004,0.830001,0.670,1.760001,15.260010,3.090002,3.950002,...,0.550000,2.100001,19.730012,3.480002,0.880001,9.460006,0.340000,1.830001,8.134884,193.57500

In [19]:
U5 = 0.5 * dh.uncertainty_data
U5

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
Date,,,,,,,,,,,,,,,,,,,,,
6/1/2005 6:00,0.03975,0.11700,0.03450,0.04350,0.017250,0.027750,0.03375,0.184500,0.15450,0.14850,...,0.004167,0.07650,1.332001,1.440001,0.02925,0.246750,0.004167,0.10500,7.933204,333.6258
6/2/2005 3:00,0.20475,0.34875,0.19125,0.10800,0.066000,0.057000,0.13800,0.276000,0.19650,0.26700,...,0.054750,0.16200,1.077751,0.465000,0.05625,0.906751,0.180750,0.16650,29.911401,545.0914
6/2/2005 6:00,0.09675,0.34950,0.09525,0.15525,0.072750,0.041250,0.11100,0.291000,0.18675,0.25050,...,0.030750,0.09000,1.476751,0.315750,0.03225,0.459000,0.039750,0.09750,5.794599,377.3470
6/3/2005 3:00,0.31275,0.50925,0.16350,0.06000,0.077250,0.059250,0.15900,0.370500,0.33675,0.40500,...,0.099750,0.26325,1.194001,0.276000,0.14325,1.257001,0.021000,0.13875,19.308555,565.2687
6/4/2005 3:00,0.11850,0.19125,0.06075,0.07500,0.040500,0.028500,0.08100,0.158250,0.15600,0.21900,...,0.045750,0.12000,1.062001,0.190500,0.04425,0.561750,0.004167,0.07050,7.638494,299.9481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9/24/2006 6:00,0.02175,0.16800,0.04650,0.34575,0.045000,0.012750,0.07275,0.895501,0.03075,0.24375,...,0.006750,0.03525,2.943002,0.339000,0.07800,0.226500,0.027000,0.21600,11.898713,571.9300
9/25/2006 6:00,0.04125,0.13200,0.03525,0.23400,0.030000,0.022500,0.08475,0.474750,0.10200,0.08625,...,0.004167,0.04425,0.614250,0.079500,0.04125,0.204000,0.017250,0.08100,11.933736,268.2000
9/26/2006 3:00,0.05100,0.10425,0.03450,0.03075,0.004167,0.004167,0.07950,0.069000,0.10200,0.08850,...,0.004167,0.03975,0.356250,0.060000,0.03000,0.196500,0.004167,0.02250,6.409994,129.5100
9/26/2006 6:00,0.08550,0.20700,0.06450,0.07425,0.035250,0.022500,0.07425,0.156750,0.26100,0.15300,...,0.030750,0.07800,0.753000,0.156000,0.02550,0.394500,0.004167,0.05100,9.916238,227.9800
9/28/2006 3:00,0.19500,0.30825,0.10950,0.46950,0.062250,0.050250,0.13200,1.144501,0.23175,0.29625,...,0.041250,0.15750,1.479751,0.261000,0.06600,0.709500,0.025500,0.13725,2.033721,387.1500

In [20]:
lower_bounds_V = dh.input_data - U5
lower_bounds_V

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
Date,,,,,,,,,,,,,,,,,,,,,
6/1/2005 6:00,0.490250,1.443001,0.425500,0.536500,0.212750,0.342250,0.416250,2.275501,1.905501,1.831501,...,0.000833,0.943501,16.428010,17.760011,0.360750,3.043252,0.000833,1.295001,23.799612,-166.81290
6/2/2005 3:00,2.525252,4.301253,2.358751,1.332001,0.814001,0.703000,1.702001,3.404002,2.423502,3.293002,...,0.675250,1.998001,13.292258,5.735004,0.693750,11.183257,2.229251,2.053501,89.734203,-272.54570
6/2/2005 6:00,1.193251,4.310503,1.174751,1.914751,0.897251,0.508750,1.369001,3.589002,2.303251,3.089502,...,0.379250,1.110001,18.213261,3.894252,0.397750,5.661004,0.490250,1.202501,17.383797,-188.67350
6/3/2005 3:00,3.857252,6.280754,2.016501,0.740000,0.952751,0.730750,1.961001,4.569503,4.153253,4.995003,...,1.230251,3.246752,14.726009,3.404002,1.766751,15.503010,0.259000,1.711251,57.925666,-282.63435
6/4/2005 3:00,1.461501,2.358751,0.749250,0.925001,0.499500,0.351500,0.999001,1.951751,1.924001,2.701002,...,0.564250,1.480001,13.098008,2.349501,0.545750,6.928254,0.000833,0.869501,22.915481,-149.97405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9/24/2006 6:00,0.268250,2.072001,0.573500,4.264253,0.555000,0.157250,0.897251,11.044507,0.379250,3.006252,...,0.083250,0.434750,36.297023,4.181003,0.962001,2.793502,0.333000,2.664002,35.696138,-285.96500
9/25/2006 6:00,0.508750,1.628001,0.434750,2.886002,0.370000,0.277500,1.045251,5.855254,1.258001,1.063751,...,0.000833,0.545750,7.575755,0.980501,0.508750,2.516002,0.212750,0.999001,35.801209,-134.10000
9/26/2006 3:00,0.629000,1.285751,0.425500,0.379250,0.000833,0.000833,0.980501,0.851001,1.258001,1.091501,...,0.000833,0.490250,4.393753,0.740000,0.370000,2.423502,0.000833,0.277500,19.229982,-64.75500
9/26/2006 6:00,1.054501,2.553002,0.795500,0.915751,0.434750,0.277500,0.915751,1.933251,3.219002,1.887001,...,0.379250,0.962001,9.287006,1.924001,0.314500,4.865503,0.000833,0.629000,29.748715,-113.99000
9/28/2006 3:00,2.405002,3.801752,1.350501,5.790504,0.767750,0.619750,1.628001,14.115509,2.858252,3.653752,...,0.508750,1.942501,18.250261,3.219002,0.814001,8.750505,0.314500,1.692751,6.101163,-193.57500

In [22]:
lower_bounds_V.describe()

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
count,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,...,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,1.338331,2.841620,0.955572,1.683646,0.568378,0.364549,1.114402,4.475604,2.154167,3.104447,...,0.399905,1.275115,14.596148,3.705667,0.596995,6.449725,0.239962,1.180333,47.401393,-199.900657
std,0.862768,2.024702,0.685231,1.616206,0.399867,0.276720,0.761979,4.370894,1.236566,1.733927,...,0.284696,0.776567,10.838306,4.043000,0.623443,3.968544,0.459213,1.786522,41.419112,121.491386
min,0.000833,0.379250,0.000833,0.000833,0.000833,0.000833,0.000833,-1.950001,0.351500,0.545750,...,0.000833,0.203500,2.090501,0.351500,0.000833,1.211751,0.000833,0.000833,0.765101,-708.467700
25%,0.758500,1.461501,0.490250,0.592000,0.314500,0.198875,0.605875,1.586376,1.304251,1.813001,...,0.222000,0.740000,7.631255,1.188626,0.249750,3.598252,0.000833,0.374625,21.692662,-249.795150
50%,1.193251,2.303251,0.758500,1.026751,0.453250,0.305250,0.971251,2.765752,1.840751,2.562252,...,0.360750,1.073001,11.349757,2.266251,0.462500,5.503753,0.083250,0.647500,37.796217,-158.820000
75%,1.725126,3.575127,1.202501,2.113626,0.721500,0.494875,1.396751,5.499128,2.622377,4.107003,...,0.541125,1.604876,17.057011,4.352128,0.818626,8.038255,0.277500,1.202501,57.440568,-113.616462
max,5.059753,12.543008,4.079253,9.712506,3.061752,2.294001,7.196505,26.917517,7.464755,8.630255,...,1.498501,4.893253,65.638041,23.032514,7.076254,24.854766,2.969252,15.984010,288.888656,-44.420000

In [23]:
dh.input_data.describe()

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
count,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,...,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,1.447004,3.072021,1.033144,1.820278,0.614610,0.394561,1.204773,4.878146,2.328829,3.356158,...,0.432850,1.378502,15.779619,4.006126,0.645961,6.972675,0.261368,1.276222,63.201858,199.900657
std,0.932473,2.188867,0.740660,1.747124,0.432080,0.298561,0.823741,4.683536,1.336828,1.874515,...,0.307049,0.839532,11.717088,4.370810,0.673456,4.290318,0.495431,1.931251,55.225483,121.491386
min,0.005000,0.410000,0.005000,0.005000,0.005000,0.005000,0.005000,0.540000,0.380000,0.590000,...,0.005000,0.220000,2.260001,0.380000,0.005000,1.310001,0.005000,0.005000,1.020135,44.420000
25%,0.820001,1.580001,0.530000,0.640000,0.340000,0.215000,0.655000,1.720001,1.410001,1.960001,...,0.240000,0.800001,8.250005,1.285001,0.270000,3.890002,0.005000,0.405000,28.923549,113.616462
50%,1.290001,2.490002,0.820001,1.110001,0.490000,0.330000,1.050001,2.990002,1.990001,2.770002,...,0.390000,1.160001,12.270008,2.450002,0.500000,5.950004,0.090000,0.700000,50.394956,158.820000
75%,1.865001,3.865002,1.300001,2.285001,0.780000,0.535000,1.510001,5.945004,2.835002,4.440003,...,0.585000,1.735001,18.440012,4.705003,0.885001,8.690005,0.300000,1.300001,76.587424,249.795150
max,5.470003,13.560008,4.410003,10.500007,3.310002,2.480002,7.780005,29.100018,8.070005,9.330006,...,1.620001,5.290003,70.960044,24.900016,7.650005,26.870017,3.210002,17.280011,385.184875,708.467700

In [2]:
import pandas as pd

,obs_date,ALf_val,ASf_val,BRf_val,CAf_val,CHLf_val,CLf_val,CRf_val,CUf_val,ECf_val,...,CM_val,CM_bext_val,dv_val,ECf_bext_val,ammNO3f_val,ammNO3f_bext_val,RCFM_val,SOILf_val,SOILf_bext_val,OMCf_val
0,19880831,0.05638,0.00000,0.00506,0.07695,0.1385,0.0,0.00000,0.00781,3.4034,...,6.33932,3.80359,26.73704,34.034,1.58606,15.98743,16.84729,1.10076,1.10076,4.67460
1,19880907,0.04586,0.00000,0.00583,0.05573,-999.0000,0.0,0.00000,0.00470,-999.0000,...,5.55478,3.33287,-999.00000,-999.000,-999.00000,-999.00000,-999.00000,0.83679,0.83679,-999.00000
2,19880910,0.09276,0.00000,0.00879,0.07595,0.0998,0.0,0.00227,0.00677,2.0428,...,-999.00000,-999.00000,-999.00000,20.428,1.01962,10.46126,35.96972,1.36909,1.36909,6.26500
3,19880914,0.07211,0.00000,0.00387,0.10184,0.0442,0.0,0.00000,0.00690,1.6568,...,7.92086,4.75252,24.19103,16.568,0.49781,5.10754,12.71179,1.48908,1.48908,2.97094
4,19880917,0.00000,0.00000,0.00814,0.05338,0.2719,0.0,0.00000,0.00505,1.3619,...,9.09144,5.45486,22.76636,13.619,1.50891,15.48145,10.60624,0.59655,0.59655,3.34796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,20020514,0.00000,0.00030,0.00223,0.03409,-0.0387,0.0,0.00000,0.00190,0.3689,...,4.37770,2.62662,19.75898,3.689,0.20459,1.84135,7.88923,0.66480,0.66480,1.30984
1370,20020517,0.00000,0.00000,0.00614,0.06067,-0.2049,0.0,0.00061,0.00388,1.0164,...,7.35920,4.41552,28.07941,10.164,1.22305,11.00744,20.64797,1.19139,1.19139,5.19498
1371,20020520,0.00000,0.00074,0.00321,0.02642,-0.1132,0.0,0.00061,0.00284,0.5679,...,2.63640,1.58184,19.75261,5.679,0.78406,7.05656,7.95640,0.54755,0.54755,1.45838
1372,20020523,0.00000,0.00075,0.00378,0.05104,-0.2926,0.0,0.00049,0.00234,0.7446,...,6.17490,3.70494,22.72161,7.446,1.04258,9.38320,11.44251,0.72020,0.72020,2.93342
1373,20020526,0.00000,0.00064,0.00778,0.04779,-0.4080,0.0,0.00040,0.00219,0.8122,...,7.76810,4.66086,29.68293,8.122,1.15765,10.41881,23.60049,0.96347,0.96347,5.11658